apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hedgedoc
  labels:
    app: hedgedoc
spec:
  rules:
    - host: pad.s2n.donkeysharp.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hedgedoc
                port:
                  number: 80
