---
galaxy_info:
  author: s2n-homelab
  description: WireGuard tunnel endpoint, in either server or client mode
  license: MIT
  min_ansible_version: '2.9'

  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie

  galaxy_tags:
    - networking
    - vpn
    - wireguard

dependencies: []
